- finat/ast.py
- finat/finiteelementbase.py
- finat/geometry_mapper.py
- finat/interpreter.py
- finat/mappers.py
This merge adds a simple mapper that inserts `ForAlls` for any unbound indices in a `Recipe`. The interpreter now invokes this mapper before evaluating a `Recipe` instead of adding implicit `ForAlls` during evaluation. The merge also includes various bugfixes.
> BindingMapper

- finat/coffee_compiler.py
- finat/pyop2_interface.py
- requirements.txt
- tests/test_coffee.py
This merge adds the final pieces for RHS assembly via FInAT and Coffee through the Firedrake `finat_loop` interface. The generated kernel code is functional for Lagrange elements with geometry and `grad` derivatives, although it is not yet optimised and currently only supports RHS assembly due to double indirections in the kernel signatures.
> Coffee RHS assembly

- finat/__init__.py
- finat/ast.py
- finat/coffee_compiler.py
- finat/indices.py
- finat/interpreter.py
- finat/mappers.py
- finat/utils.py
- tests/test_index_permutation.py
This branch deals with the fact that the order of the ForAll statements may not correspond with the order in which the indices occur in Recipes. Recipe objects now record the required generalised transpose and the interpreter honours this.
As part of this work, the BindingMapper is now stateless and passes binding information as arguments rather than as attributes of the mapper object.
There is an xfailing test for the coffee compiler which highlights that this fix has not been applied there yet. That xfailing test highlights a further issue with the coffee compiler's handing of multiple ForAll statements.
> Index permuation

- finat/fiat_elements.py
- finat/point_set.py
- finat/tensorfiniteelement.py
This change makes FInAT report if a basis function is cellwise constant, so TSFC can optimise evaluation. This is achieved through an **API change**:
`basis_evaluation` no longer returns point structure as shape, but rather as free indices. If the value of the basis functions does not depend on some point indices, then those indices simply won't appear in the free indices of the return expression.
> Report if basis functions are cellwise constant

- finat/__init__.py
- finat/point_set.py
- finat/quadrature_element.py
Similar to `QuadratureElement` in FFC, but this one returns symbolic identity matrices (GEM `Delta` nodes) rather than numerical ones, which makes it much easier to simplify away coefficient and maybe even argument evaluations.
> Add QuadratureElement

- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/quadrature_element.py
- finat/quadrilateral.py
- finat/sympy2gem.py
- finat/tensor_product.py
- finat/tensorfiniteelement.py
Resolves #26.
This brings us closer to generate code for the evaluation of UFL expressions/forms at reference points that are only known at run time.
Structured evaluation code is provided for:
- Ciarlet finite elements
- Tensor product elements
- Vector/tensor elements
Not particularly good, but working evaluation code is generated for all other element types.
> Point evaluation

- finat/finiteelementbase.py
Use GEM interpreter instead of `gem.optimise.aggressive_unroll`.
Requires firedrakeproject/tsfc#129.
Resolves firedrakeproject/firedrake#1098.
> Faster entity_support_dofs

- finat/__init__.py
- finat/fiat_elements.py
- finat/point_set.py
- finat/quadrature.py
- finat/spectral.py
... for the zeroth derivative if tabulation points match the node locations.
Already works for Gauss-Legendre elements since default line quadrature from FIAT is Gauss-Legendre. Work for Gauss-Lobatto-Legendre as well if one manually provides the correct quadrature rule.
> Spectral elements return symbolic identity matrices

- finat/__init__.py
- finat/mixed.py
- finat/tensorfiniteelement.py
Add a structured mixed element implemented through `EnrichedElement`, and make `TensorFiniteElement` "transposable": vector/tensor indices may come after or before the scalar basis function indices.
> Mixed element and "transposable" tensor element

- finat/__init__.py
- finat/discontinuous.py
- finat/fiat_elements.py
- finat/trace.py
Also adds a FInAT implementation of `ufl.BrokenElement`, similar to `FIAT.DiscontinuousElement`. So one can have, for example, a structured broken RTCF element.
> Add wrappers for more FIAT elements

- finat/point_set.py
- finat/tensor_product.py
A singleton point set. Useful when something needs evaluation at one fixed point, such as `CellOrigin`, Hermite element transformations, etc.
> Add PointSingleton

- finat/quadrilateral.py
- finat/tensor_product.py
Previously, computation of entity_support_dofs did not exploit tensor
product structure, and so at high order, required allocation of
temporaries of size O(p^2d).  Fix this by computing the support dofs
on the element factors and productising them.
> Fix excessive memory consumption in entity_support_dofs

- finat/enriched.py
- finat/hdivcurl.py
- finat/mixed.py
I need this for more elements in order to run high-order H(div) and H(curl) elements.
> Fix excessive memory consumption in entity_support_dofs: Part 2

- finat/spectral.py
There are a couple of coordinate mapping checks on spectral elements which do not appear for equispaced elements and which don't seem to have a purpose, but which break things.
> Remove overenthusiastic checks

- finat/enriched.py
Catches a case where someone built an enriched element with only a
single subelement, which subsequently dies in tree_map(max, ...)
because that implicitly relies on there being at least two
arguments (such that mapping max works).
Fixes firedrakeproject/firedrake#1762.
> enriched: Return subelement for single argument

- requirements-git.txt
This typo makes me wonder if these `#egg=` specifications are required or useful at all.
> Fix age-old typo

- finat/__init__.py
- finat/cube.py
- finat/discontinuous.py
- finat/enriched.py
- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/hdivcurl.py
- finat/nodal_enriched.py
- finat/quadrature_element.py
- finat/tensor_product.py
- Adds `.fiat_equivalent` property that gives the equivalent FIAT element for any particular FInAT element.
- Mostly implemented as `cached_property`, so as to simulate the caching feature of the FIAT interface in TSFC.
> Add ability to construct the equivalent FIAT element

- finat/fiat_elements.py
We do need to obey index_shape, but we need to generate indices whose
extents match index_shape.
> Fix tabulation for zany elements

- finat/__init__.py
- finat/fiat_elements.py
Kong-Mulder-Veldhuizen elements are higher-order, mass-lumpable simplicial elements.  This PR wraps up the associated elements in FIAT.
> Add KMV elements

- finat/quadrature_element.py
This fixes
```
from firedrake import *
from ufl.geometry import QuadratureWeight
mesh = UnitSquareMesh(2, 1, quadrilateral=True)
gdim = mesh.geometric_dimension()
V = FunctionSpace(mesh, "CG", 1)
Qse = FiniteElement("Quadrature", mesh.ufl_cell(), degree=2, quad_scheme="default")
Qs = FunctionSpace(mesh, Qse)
Qte = TensorElement("Quadrature", mesh.ufl_cell(), degree=2, quad_scheme="default", shape=(gdim, gdim))
Qt = FunctionSpace(mesh, Qte)
x = SpatialCoordinate(mesh)[0]
xq = interpolate(x, Qs)
print("Coordinate: ")
print(xq.dat.data_ro)
print("x-coordinates of quadrature points on cell 0: ")
print(xq.dat.data_ro[Qs.cell_node_map().values[0]])
Jinv = JacobianInverse(mesh)
Jdet = JacobianDeterminant(mesh)
w = QuadratureWeight(mesh)
G = dot(Jinv.T, Jinv) * Jdet
Gq = interpolate(G, Qt) …
```
> Always give weights to a QuadratureElement.

- requirements-git.txt
Update fiat package name to fenics-fiat. Aims to fix this problem during install on CI:
```
ERROR: Could not find a version that satisfies the requirement fiat (unavailable)
ERROR: No matching distribution found for fiat (unavailable)
Error: Process completed with exit code 1.
```
Similar to https://github.com/firedrakeproject/tsfc/pull/238
> Update package names for installation CI

- finat/point_set.py
Aims to avoid any ambiguity or confusion about the expected shape of the `__init__` arguments and generally avoid the silly confusion that led to me making 3b19867bb15cdcac1b7accea73c38108f0fe46b0
> Add docstrings to PointSingleton and PointSet

- finat/__init__.py
- finat/point_set.py
- finat/quadrature.py
- finat/quadrature_element.py
Adds a new `UnknownPointSingleton` which represents a single point which is specified at run time. 
`UnknownPointSingleton`s are typically intended for use as the point set in the rule of a `QuadratureElement`: the `QuadratureElement` acts as a target element on the reference cell when performing dual basis evaluation on some other element for run time specified points. A typical use case is when performing dual evaluation across different elements on different domains. By only specifying an `UnknownPointSingleton` (rather than a full `UnknownPointSet`), only runtime evaluation at single points can be supported at present. 
The `QuadratureElement` API has been suitably adjusted and a compatibility function added.
These changes are needed to allow interpolation from an arbitrary function …
> Runtime point set for use with QuadratureElement

- finat/quadrature_element.py
This fixes #90: the wrong FIAT reference element dimension was being
checked against in the case of a tensor product cells
> Compare to spatial dim when making QuadratureElement

- finat/cube.py
- finat/discontinuous.py
- finat/enriched.py
- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/hdivcurl.py
- finat/tensor_product.py
This PR is to add entity_permutations `method` to basic finite FInAT elements (such as `TensorProductElement`) that defines a DoF permutation (to be used in global vector assembly) for each possible entity orientation for each entity for each dimension.
`entity_permutations` returns `None` if it is not yet implemented for that element, so the problem solving environment must handle this correctly if it ever tries to use this method.
Requires:
https://github.com/firedrakeproject/fiat/pull/25
> orientations: define entity_permutations() method for basic finite elements

- finat/hdivcurl.py
- finat/tensor_product.py
Progress towards having duals for all finat element modifiers. The big missing one now is `EnrichedElement`.
This change also showed up a bug in the implementation of the dual for tensor product elements (if any of the factors had value_shape).
> Dual for hdiv/hcurl element wrappers

- finat/tensor_product.py
Enhance `entity_permutations` of tensorproduct elements so that "extrinsic" orientation can happen when mapping the reference cell to the physical cell.
Example (Interval x Interval x Interval):
Extrinsic orientations: X -> y, Y->z, Z->x, etc. (3! ways)
Intrinsic orientations: X->-X, Y->-Y, etc. (2^3 ways per extrinsic orientation)
This gives 3! * (2^3) = 48 ways of mapping the reference cell to the physical cell.
> orientation: handle extrinsic orientations in tensor product elements

- .github/workflows/docs.yml
- .github/workflows/test.yml
The docs build also needs to run on 3.8. Further, update the uses calls to v3 to avoid deprecation warnings.
> Update workflow specifications

- finat/point_set.py
- finat/tensor_product.py
- finat/ufl/__init__.py
- finat/ufl/brokenelement.py
- finat/ufl/elementlist.py
- finat/ufl/enrichedelement.py
- finat/ufl/finiteelement.py
- finat/ufl/finiteelementbase.py
- finat/ufl/hdivcurl.py
- finat/ufl/mixedelement.py
- finat/ufl/restrictedelement.py
- finat/ufl/tensorproductelement.py
- requirements-git.txt
- setup.py
This change follows on from https://github.com/FEniCS/ufl/pull/197, and needs this to be merged into the Firedrake fork of UFL.
Moving UFL element code to FInAT so that `ufl.legacy` can be removed.
This is intended to be a temporary solution. Longer term, the plan could be to make finat elements inherit from `ufl.AbstractFiniteElement` so that they can be used directly without this wrapper code.
This PR will allow https://github.com/firedrakeproject/firedrake/pull/3166, https://github.com/firedrakeproject/tsfc/pull/302, and https://github.com/NGSolve/ngsPETSc/pull/7 to be done.
If these four PRs are merged (and the latest UFL is merged into the Firedrake fork), the the UFL elements used by Firedrake will all be defined in FInAT (currently in `finat.ufl`). This code can then gradually be …
> Move ufl legacy elements to finat

- finat/ufl/finiteelement.py
This appears to fix https://github.com/firedrakeproject/firedrake/issues/3251. However, I'm not familiar enough with UFL to be confident that this is the right thing to do. Is it legal for a "base" finite element to have non-integer `degree`?
> Allow embedded_subdegree and embedded_superdegree to handle tuples

- finat/fiat_elements.py
- requirements-git.txt
It seems that we did not really need a special case for point evaluation of Ciarlet elements. 
Instead of directly tabulating an element on a sympy Variable, we were evaluating the expansion set and manipulating the expansion coefficients trying to simplify tabulations that result in constants, e. g. second derivatives of Lagrange(2). Operating at the expansion coefficient level will only simplify constants when the constant function is a member of the expansion set, which is not true for a LagrangeLineExpansionSet.
It turns out that a special case for Ciarlet is not necessary, as `gem.ListTensor` has constant folding.
https://github.com/firedrakeproject/tsfc/blob/5515b2ae3c19e41bf80f347e7259fe9f5d86a9a2/gem/gem.py#L724
Tests that were failing are passing with this PR and …
> Tabulate Ciarlet generically

- finat/fiat_elements.py
This is a bug that we weren't hitting before. `map(max, *Q)` would break if `Q = {(0, 0): X}`. This occurs when you define DG0 with an IntegralMoment with quadrature degree=0, (which we now hit if variant="integral")
> Fix dual basis for singleton weight

- finat/ufl/finiteelementbase.py
- test/test_hash.py
The current implementation produces a different hash for different Python invocations. This means the value cannot safely be used for a (persistent) disk cache.
The new implementation replaces the inbuilt Python `hash` with `md5`, which produces the same result across invocations.
Someone with better knowledge of FInAT should double check that all relevant data is encoded in `self._ufl_hash_data_()` , which I believe is just the repr of whatever the derived object is.
> Use md5 to hash FiniteElementBase
