FInAT/FInAT

- .travis.yml
- finat/__init__.py
- finat/ast.py
- finat/bernstein.py
- finat/coffee_compiler.py
- finat/geometry_mapper.py
- finat/greek_alphabet.py
- finat/hdiv.py
- finat/indices.py
- finat/interpreter.py
- finat/lagrange.py
- finat/mappers.py
- finat/product_elements.py
- requirements.txt
- tests/demo_graphviz.py
- tests/test_bernstein.py
- tests/test_coffee.py
We've got stuck in a slightly unfortunate position where there are lots of cross-dependencies between feature branches. This is at least as much my fault as everyone else, although it's largely due to us being at such an early and rapidly changing stage of development.
This branch sits on top of all current developments and I have taken the necessary steps to make the tests pass. Accordingly, I'm making an "executive" decision to merge current development to master.
Moving forward, the preferred development model is to have very short-lived branches which are rebased on master as it moves. Merging branches (as opposed to rebasing) should be avoided as much as possible.
> Ufl interface

- .travis.yml
- Makefile
- finat/__init__.py
- finat/ast.py
- finat/finiteelementbase.py
- finat/geometry_mapper.py
- finat/indices.py
- finat/interpreter.py
- finat/mappers.py
- finat/points.py
- finat/product_elements.py
- finat/quadrature.py
- finat/scalar_elements.py
- finat/ufl_interface.py
- finat/utils.py
- finat/vectorfiniteelement.py
- requirements.txt
- tests/test_coffee.py
Merge in previously working code before we discard it.
> Tensor elements

- .travis.yml
- finat/__init__.py
- finat/bernstein.py
- finat/derivatives.py
- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/gauss_jacobi.py
- finat/greek_alphabet.py
- finat/points.py
- finat/product_elements.py
- finat/quadrature.py
- finat/ufl_interface.py
- finat/vectorfiniteelement.py
- setup.cfg
- setup.py
Enables testing with Python in Travis CI, forces a few basic `__future__` imports, notably absolute imports and Python 3 divisions.
> Python 3 compatibility improvements

- finat/fiat_elements.py
Currently, value shape is the last part of FInAT tabulation matrices, both externally (GEM shape) and internally (Literal tensor inside, except when `TensorElement` is used). For elements still working via the FIAT backwards compatibility layer, this internal representation produces an ugly layout for the tables in the generated code, which is difficult to optimise. This change implements a splitting similar to `tsfc.fem.tabulate` (master), so that the generated code looks more like previously.
Requires firedrakeproject/tsfc#83.
> Split value components of FIAT tabulation matrices

- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/quadrilateral.py
- finat/tensor_product.py
- finat/tensorfiniteelement.py
> FIAT-compatible API for node allocation

- .travis.yml
- finat/fiat_elements.py
- requirements-ext.txt
- test/test_point_evaluation_ciarlet.py
Resolves #30. Adds the first ever unit test in FInAT.
> Cellwise constantness aware code generation for the point evaluation of Ciarlet elements

- finat/__init__.py
- finat/enriched.py
The FInAT version of `FIAT.EnrichedElement`. Related to #19.
Requires firedrakeproject/tsfc#131.
> Enriched element

- finat/__init__.py
- finat/enriched.py
- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/hdivcurl.py
- finat/quadrilateral.py
- finat/tensor_product.py
- finat/tensorfiniteelement.py
> Add H(div) and H(curl) element wrappers

- finat/finiteelementbase.py
- finat/quadrilateral.py
Make the interface for entity_support_dofs the same as that for entity_closure_dofs (i.e. that we can ask the element directly).
> Esd method

- finat/__init__.py
- finat/chris.py
- finat/runtime_tabulated.py
Used in TSFC/Themis integration.
> Add runtime tabulated element

- finat/finiteelementbase.py
See https://bitbucket.org/fenics-project/fiat/issues/21.
> Fix FIAT issue 21

- finat/__init__.py
- finat/argyris.py
- finat/bell.py
- finat/fiat_elements.py
- finat/morley.py
- finat/physically_mapped.py
- setup.cfg
Registered Serendipity element, removed a line in basis_evaluation that causes Helmholtz tests to fail
> Serendipity

- finat/__init__.py
- finat/enriched.py
- finat/restricted.py
- test/test_restriction.py
This pushes everything through the element algebra, rather than masking out dofs that we want to drop. I think this is the best way.
> Implement RestrictedElement

- LICENSE
- README.md
Please have a look and comment!
Resolves #62.
> An attempt at revising the README file

- finat/aw.py
Small changes to the FInAT file for the Arnold--Winther elements, to make the transformation of the internal DOFs consistent with the zany theory, and to post-hoc rescale the DOFs so as to give the mass matrices O(1) conditioning.
> AWconditioning

- finat/__init__.py
- finat/enriched.py
- finat/fiat_elements.py
Here I have:
- Introduced `finat.Real`
- Added a `is_mixed` method to `EnrichedElement`
> Add Real element

- finat/__init__.py
- finat/spectral.py
Adds a wrapper for continuous 1D elements with FDM shape functions.
Depends on [FIAT#26](https://github.com/firedrakeproject/fiat/pull/26).
> Wrap FIAT.FDMLagrange

- finat/enriched.py
Expand nested `EnrichedElement`s into a single `EnrichedElement`.
This fixes the issue https://github.com/firedrakeproject/firedrake/issues/2713
> Expand EnrichedElement

- finat/tensor_product.py
Some refactoring related to https://github.com/firedrakeproject/fiat/pull/37.
Depends on https://github.com/firedrakeproject/fiat/pull/37
> refactor: make tensorproduct permutations in FIAT

- finat/ufl/brokenelement.py
- finat/ufl/hdivcurl.py
Fixes https://github.com/firedrakeproject/firedrake/issues/3243 and https://github.com/firedrakeproject/firedrake/issues/3244.
Note that tests are failing here because of a separate ([reported](https://github.com/FInAT/FInAT/issues/114)) issue.
> Add missing embedded_superdegree and embedded_subdegree properties

- finat/__init__.py
- finat/bell.py
- finat/cell_tools.py
- finat/cube.py
- finat/direct_serendipity.py
- finat/discontinuous.py
- finat/enriched.py
- finat/fiat_elements.py
- finat/finiteelementbase.py
- finat/hct.py
- finat/hdivcurl.py
- finat/mixed.py
- finat/physically_mapped.py
- finat/quadrature.py
- finat/quadrature_element.py
- finat/spectral.py
- finat/tensor_product.py
- finat/tensorfiniteelement.py
- finat/ufl/elementlist.py
- test/fiat_mapping.py
- test/test_hct.py
Advertise a reference complex in case the basis functions are defined on a split cell.
Implement the HCT triangle and its basis transformation.
Depends on https://github.com/firedrakeproject/fiat/pull/64
> C0/C1 Macroelements

- finat/sympy2gem.py
This is required to make MG work with macro elements
> GEM: sympy2gem conditional support

- finat/sympy2gem.py
More sympy2gem for more complicated boolean expressions
> sympy2gem: if-then-else

- finat/__init__.py
- finat/alfeld_sorokina.py
- finat/bernardi_raugel.py
- finat/guzman_neilan.py
- finat/physically_mapped.py
- finat/piola_mapped.py
- finat/ufl/elementlist.py
- finat/ufl/enrichedelement.py
- finat/ufl/finiteelement.py
- finat/ufl/mixedelement.py
- test/test_zany_mapping.py
Depends on https://github.com/firedrakeproject/fiat/pull/86
> Guzman-Neilan H1(div) macroelement

- finat/__init__.py
- finat/argyris.py
- finat/aw.py
- finat/bell.py
- finat/fiat_elements.py
- finat/hct.py
- finat/hz.py
- finat/mtw.py
- finat/physically_mapped.py
- finat/piola_mapped.py
- finat/ufl/elementlist.py
- finat/ufl/finiteelementbase.py
- test/test_zany_mapping.py
> Allow HHJ in 3D
